version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - FRONTEND_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$FRONTEND_IMAGE_REPO_NAME
      - BACKEND_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BACKEND_IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the frontend Docker image...
      - docker build -t $FRONTEND_REPO_URI:latest ./frontend
      - docker tag $FRONTEND_REPO_URI:latest $FRONTEND_REPO_URI:$IMAGE_TAG
      - echo Building the backend Docker image...
      - docker build -t $BACKEND_REPO_URI:latest ./backend
      - docker tag $BACKEND_REPO_URI:latest $BACKEND_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the frontend Docker image...
      - docker push $FRONTEND_REPO_URI:latest
      - docker push $FRONTEND_REPO_URI:$IMAGE_TAG
      - echo Pushing the backend Docker image...
      - docker push $BACKEND_REPO_URI:latest
      - docker push $BACKEND_REPO_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"},{"name":"%s","imageUri":"%s"}]' "$FRONTEND_IMAGE_REPO_NAME" "$FRONTEND_REPO_URI:$IMAGE_TAG" "$BACKEND_IMAGE_REPO_NAME" "$BACKEND_REPO_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
